# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Cache@2
  displayName: 'Register TF cache'
  inputs:
    key: terraform | $(Agent.OS) | "$(Build.BuildNumber)" | $(Build.SourceVersion) | $(tfComponent) | "$(tfVarFileName)"
    path: $(tfExecutionDir)

- task: TerraformTaskV3@3
  inputs:
    provider: 'gcp'
    command: 'init'
    backendServiceGCP: 'gcp-tf'
    backendGCPBucketName: 'azure-tf'
